[project]
name = "mae5810-code"
version = "0.1.0"
description = "Simulation code for assignments and projects for MAE 5810"
readme = "README.md"
authors = [
    { name = "Thomas Istvan", email = "tommyjohnhawaii@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pyqt5>=5.15.11",
]

[project.scripts]
mae5810-code = "mae5810_code:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
